/* eslint-disable */
/**
 * Generated Convex API stub
 * This file is auto-generated by Convex. When Convex is properly configured,
 * run `npx convex dev` to regenerate this file with the actual API.
 */

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 * This is a stub - run `npx convex dev` to generate the real API.
 */
export const api = anyApi as any;

/**
 * A utility for referencing Convex functions in your app's internal API.
 */
export const internal = anyApi as any;
