/* eslint-disable */
/**
 * Generated Convex data model stub
 * This file is auto-generated by Convex. When Convex is properly configured,
 * run `npx convex dev` to regenerate this file.
 */

import type { DataModelFromSchemaDefinition } from "convex/server";

export type DataModel = any;
export type Doc<T extends string> = any;
export type Id<T extends string> = string;
